image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

build_job:
  stage: build
  image: docker:latest
  environment:
    name: branch/${CI_COMMIT_REF_NAME}
  script:
    - echo 'Building'
    - docker rm -f reddit-${CI_ENVIRONMENT_SLUG}
    - docker build -t reddit:${CI_ENVIRONMENT_SLUG} docker-monolith/
    - docker run --name reddit-${CI_ENVIRONMENT_SLUG} --publish-all --detach reddit:${CI_ENVIRONMENT_SLUG}

test_unit_job:
  stage: test
  before_script:
    - cd reddit
    - bundle install
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  image: docker:latest
  script:
    - REDDIT_PORT=$(docker port reddit-${CI_ENVIRONMENT_SLUG} 9292/tcp | head -n 1 | awk -F ':' '{print $2}')
    - echo "Deploy to $CI_ENVIRONMENT_SLUG at port ${REDDIT_PORT}"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://${CI_SERVER_HOST}:${REDDIT_PORT}
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: beta
    url: http://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: http://example.com
