---
- name: Check && install Python
  hosts: _reddit_docker
  become: true
  gather_facts: False

  tasks:
    - name: Install Python for Ansible
      raw: test -e /usr/bin/python3 || (apt-get -y update && apt-get -y install python3-minimal python3-pip)
      changed_when: False
